import fs from "node:fs/promises";
import path from "node:path";

const ROOT = "/Users/ashi/github/informatics_club";
const ARTIFACT_TOOL =
  "/Users/ashi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs";

const { PresentationFile, FileBlob } = await import(ARTIFACT_TOOL);

const SOURCE = path.join(ROOT, "sctalk/06_seurat-vs-scanpy/06_sctalk0906.pptx");
const OUT = path.join(ROOT, "sctalk/06_seurat-vs-scanpy/06_sctalk0906_with_supplemental.pptx");
const MANIFEST = path.join(
  ROOT,
  "outputs/manual-20260609-richsupp/presentations/rich-supplement/assets/supp_manifest.json",
);

const SLIDE = { width: 1280, height: 720 };
const IMAGE_BOX = { left: 300, top: 12, width: 860, height: 640 };
const SUBTITLE_FRAME = { left: 58, top: 132, width: 235, height: 96 };
const MAIN_SUBTITLE_FRAME = { left: 220, top: 88, width: 850, height: 38 };

const MAIN_FIGURE_LEGENDS = {
  1: "Figure 1. Seurat and Scanpy show considerable differences in scRNA-seq workflow results with default function arguments. (A) Filtering and HVG selection analysis UpSet plots consisting of sets of (Ai) cells, (Aii) genes, and (Aiii) HVGs. (B) (Bi) PCA through projection onto the first two PCs. (Bii) Scree plot and the sine of eigenvectors. Black lines = point mapping between conditions. (C) KNN/SNN analysis through SNN neighborhood Jaccard index and degree ratio (Seurat/Scanpy) per cell. (D) Clustering and UMAP analysis through UMAP plots of Seurat (left) and Scanpy (right), with the alluvial diagram (middle) showing cluster assignment mapping and degree of cluster agreement. Numbers at the bottom of the alluvial diagram represent the total number of clusters in each group. (E) DE analysis UpSet plot through overlap of all significant (p < 0.05) marker genes across all clusters. Dataset used: 10,000 PBMC.",
  2: "Figure 2. Reads and cells can be downsampled to small fractions before reaching the level of differences observed between Seurat and Scanpy on the same data. (A) Subsampling of reads. (B) Subsampling of cells. Subsampling was performed at fractions ranging from 1% to 64%. Orange represents Seurat; blue represents Scanpy.",
  3: "Figure 3. Package versioning has significant implications for DE analysis. (A-C) Seurat v5 vs. v4 differences in (A) significant and total marker selection, (B) logFC, and (C) adjusted p value calculation. (D-F) Scanpy v1.9 vs. v1.4 differences in (D) significant and total marker selection, (E) logFC, and (F) adjusted p value calculation. (G-I) Cell Ranger v7 vs. v6 differences in (G) significant and total marker selection, (H) logFC, and (I) adjusted p value calculation.",
  4: "Figure 4. Additional analysis underscores observed differences between Seurat and Scanpy in biologically motivated downstream analysis. (A) Alluvial plot showing cell-type mapping between Seurat and Scanpy default pipelines. (B) Volcano plot for differentially expressed genes identified by Seurat in cluster 15. (C) Volcano plot for differentially expressed genes identified by Scanpy in cluster 15. Biological significance thresholds used (dashed lines): |log FC| = 1 (vertical) and p = 0.05 (horizontal). Red = significantly upregulated; blue = significantly downregulated; gray = no significant difference. (D) UpSet plots of the set comparison for the biologically significant (i.e., red and blue) genes selected from the volcano plots generated by Seurat and Scanpy in cluster 15. (E) GO analysis scatterplot from the Enrichr \"pathway\" database, given the biologically significant genes identified by Seurat and Scanpy in cluster 15. Dataset: 10,000 PBMC.",
};

const MAIN_SLIDE_TITLES = new Map([
  [7, { figure: 1, title: "Default workflows diverge in filtering and HVGs" }],
  [8, { figure: 1, title: "Default workflows diverge in PCA and SNN graphs" }],
  [9, { figure: 1, title: "Default workflows diverge in clustering, UMAP and DE" }],
  [10, { figure: 2, title: "Downsampling reaches Seurat-vs-Scanpy variability" }],
  [
    11,
    {
      figure: 3,
      title: "Package and Cell Ranger versions reshape DE",
      frame: { left: 58, top: 136, width: 220, height: 90 },
    },
  ],
  [
    12,
    {
      figure: 4,
      title: "Cell-type, DE and pathway results diverge downstream",
      frame: { left: 58, top: 136, width: 138, height: 130 },
    },
  ],
]);

function shapeText(shape) {
  return shape?.text?.toString?.() ?? "";
}

function slideTexts(slide) {
  return slide.shapes.items.map(shapeText).filter(Boolean);
}

function isOldSupplementSlide(slide) {
  return slideTexts(slide).some((text) => /^FigS\d+\.\s*$/i.test(text.trim()));
}

function fitFrame(record) {
  const scale = Math.min(IMAGE_BOX.width / record.width, IMAGE_BOX.height / record.height);
  const width = record.width * scale;
  const height = record.height * scale;
  return {
    left: IMAGE_BOX.left + (IMAGE_BOX.width - width) / 2,
    top: IMAGE_BOX.top + (IMAGE_BOX.height - height) / 2,
    width,
    height,
  };
}

function setText(shape, text) {
  if (!shape) return;
  shape.text = text;
}

function styleSubtitle(shape) {
  try {
    shape.text.fontSize = 18;
    shape.text.color = "#365344";
    shape.text.typeface = "Aptos";
  } catch {
    // Imported decks can expose limited text styling on some placeholder shapes.
  }
}

function addSubtitle(slide, text) {
  const subtitle = slide.shapes.add({
    geometry: "rect",
    position: SUBTITLE_FRAME,
    fill: { color: "#FFFFFF", transparency: 100 },
    line: { color: "#FFFFFF", transparency: 100 },
  });
  subtitle.text = text;
  styleSubtitle(subtitle);
  return subtitle;
}

function addMainSubtitle(slide, text, frame = MAIN_SUBTITLE_FRAME) {
  const subtitle = slide.shapes.add({
    geometry: "rect",
    position: frame,
    fill: { color: "#FFFFFF", transparency: 100 },
    line: { color: "#FFFFFF", transparency: 100 },
  });
  subtitle.text = text;
  styleSubtitle(subtitle);
  return subtitle;
}

function addMainFigureMetadata(presentation) {
  for (const [slideNumber, metadata] of MAIN_SLIDE_TITLES.entries()) {
    const slide = presentation.slides.items[slideNumber - 1];
    if (!slide) continue;
    addMainSubtitle(slide, metadata.title, metadata.frame);
    slide.speakerNotes.setText(
      [
        `Figure ${metadata.figure}. ${metadata.title}`,
        "",
        MAIN_FIGURE_LEGENDS[metadata.figure],
        "",
        `Source: Rich et al., Cell Systems 2026, combined paper + supplement PDF.`,
      ].join("\n"),
    );
  }
}

function findTitleShape(slide) {
  return slide.shapes.items.find((shape) => /^FigS\d+\.\s*$/i.test(shapeText(shape).trim()));
}

function findMarkerShape(slide) {
  return slide.shapes.items.find((shape) => /^\d+\s*$/.test(shapeText(shape).trim()));
}

function removeSlideById(presentation, slideId) {
  const index = presentation.slides.items.findIndex((slide) => slide.id === slideId);
  if (index >= 0) {
    presentation.slides.remove(index);
  }
}

const manifest = JSON.parse(await fs.readFile(MANIFEST, "utf8"));
const presentation = await PresentationFile.importPptx(await FileBlob.load(SOURCE));
addMainFigureMetadata(presentation);

const oldSupplementSlides = presentation.slides.items.filter(isOldSupplementSlide);
if (!oldSupplementSlides.length) {
  throw new Error("Could not find a FigS template slide in the source deck.");
}

const blankTemplate =
  oldSupplementSlides.find((slide) => slide.images.items.length === 0) ?? oldSupplementSlides[0];
const oldSupplementIds = oldSupplementSlides.map((slide) => slide.id);
const template = blankTemplate.duplicate();
template.moveTo(presentation.slides.items.length - 1);

for (const slideId of oldSupplementIds) {
  removeSlideById(presentation, slideId);
}

const appendedSlides = [];
for (const record of manifest) {
  const slide = template.duplicate();
  slide.moveTo(presentation.slides.items.length - 1);

  setText(findTitleShape(slide), `${record.label} `);
  addSubtitle(slide, record.title);

  const imageData = await fs.readFile(record.image);
  slide.images.add({
    data: imageData,
    contentType: "image/png",
    frame: fitFrame(record),
    alt: `${record.label} ${record.title}`,
    fit: "contain",
  });

  slide.speakerNotes.setText(
    [
      `${record.label} ${record.title}`,
      "",
      record.legend,
      "",
      `Source: Rich et al., Cell Systems 2026, supplemental PDF page ${record.sourcePage}.`,
    ].join("\n"),
  );
  appendedSlides.push(slide);
}

removeSlideById(presentation, template.id);

for (const slide of appendedSlides) {
  const marker = findMarkerShape(slide);
  const finalNumber = presentation.slides.items.findIndex((candidate) => candidate.id === slide.id) + 1;
  setText(marker, String(finalNumber));
}

for (const slide of presentation.slides.items) {
  slide.setViewportSize(SLIDE.width, SLIDE.height);
}

const pptx = await PresentationFile.exportPptx(presentation);
await pptx.save(OUT);

console.log(JSON.stringify({
  source: SOURCE,
  output: OUT,
  originalSlideCount: 22,
  removedPartialSupplementSlides: oldSupplementIds.length,
  appendedSupplementSlides: appendedSlides.length,
  finalSlideCount: presentation.slides.count,
}, null, 2));
